// frontendEagledac/src/components/DeployConsole.tsx

import { useEffect, useRef, useState } from "react";
import "../styles/deploy.scss";

import { useAccount, useWalletClient } from "wagmi";
import { abi } from "../contracts/GeneratedDAC-abi";
import bytecode from "../contracts/GeneratedDAC-bytecode";
import WalletConnector from "./WalletConnector";

function DeployConsole() {
  const [logs, setLogs] = useState<string[]>([]);
  const [txHash, setTxHash] = useState<string | null>(null);
  const [deploying, setDeploying] = useState(false);
  const [dacCount, setDacCount] = useState<number>(0);
  const consoleRef = useRef<HTMLDivElement>(null);

  const { data: walletClient } = useWalletClient();
  const { address } = useAccount();

  const fetchCount = async () => {
    try {
      const res = await fetch("http://localhost:3001/api/dac-count");
      const data = await res.json();
      setDacCount(data.count);
    } catch (error) {
      console.error("❌ Error fetching DAC count:", error);
    }
  };

  const handleDeploy = async () => {
    if (!walletClient || !address) {
      setLogs((prev) => [...prev, "❌ Wallet not connected"]);
      return;
    }

    try {
      setDeploying(true);
      setLogs(["🚀 Starting deployment..."]);

      const hash = await walletClient.deployContract({
        abi,
        bytecode,
        args: ["This DAC was generated by EagleDAC 🦅"],
        account: address,
      });

      setLogs((prev) => [...prev, `📡 Tx Hash: ${hash}`]);
      setTxHash(hash);

      // Incrementar contador
      await fetch("http://localhost:3001/api/dac-count/increment", {
        method: "POST",
      });

      await fetchCount(); // refrescar número
    } catch (err: unknown) {
      if (err instanceof Error) {
        setLogs((prev) => [...prev, `❌ Error: ${err.message}`]);
      } else {
        setLogs((prev) => [...prev, "❌ Unknown error"]);
      }
    } finally {
      setDeploying(false);
    }
  };

  useEffect(() => {
    fetchCount();
  }, []);

  useEffect(() => {
    const el = consoleRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [logs]);

  return (
    <div className="deploy-console">
      <h2>🚀 Deploy Smart Contract</h2>
      <WalletConnector />

      <p className="counter-display">
        🧮 Total DACs deployed: <strong>{dacCount}</strong>
      </p>

      <button onClick={handleDeploy} disabled={deploying}>
        {deploying ? (
          <>
            <span className="spinner" /> Deploying...
          </>
        ) : (
          "🚀 Deploy DAC"
        )}
      </button>

      <div className="console-output" ref={consoleRef}>
        {logs.map((line, idx) => (
          <pre
            key={idx}
            className={
              line.includes("✅")
                ? "log-success"
                : line.includes("❌")
                ? "log-error"
                : ""
            }
          >
            {line}
          </pre>
        ))}
      </div>

      {txHash && (
        <div className="deploy-success">
          <p>✅ Deployed to:</p>
          <a
            href={`https://andromeda-explorer.metis.io/tx/${txHash}`}
            target="_blank"
            rel="noopener noreferrer"
          >
            {txHash}
          </a>
        </div>
      )}
    </div>
  );
}

export default DeployConsole;
